cl-start-all:
	cd ./courier/    ; make cl-start & cd ../ ; \
	cd ./customer/   ; make cl-start & cd ../ ; \
	cd ./restaurant/ ; make cl-start

update-gomod-all:
	cd ./courier/    ; make update-gomod ; cd ../ ; \
    cd ./customer/   ; make update-gomod ; cd ../ ; \
    cd ./restaurant/ ; make update-gomod

download-gomod-all:
	cd ./courier/    ; make download-gomod ; cd ../ ; \
    cd ./customer/   ; make download-gomod ; cd ../ ; \
    cd ./restaurant/ ; make download-gomod

gomod-tidy-all:
	cd ./courier/    ; make gomod-tidy ; cd ../ ; \
    cd ./customer/   ; make gomod-tidy ; cd ../ ; \
    cd ./restaurant/ ; make gomod-tidy
