server:
  rest:
    address: ":8080"
    readTime: "5s"
    writeTime: "5s"
    idleTime: "5m"
    readerHeaderTime: "5s"
  grpc:
    address: ":140"
database:
  host: "host.docker.internal"
  port: 5430
  user: "accounting_db"
  password: "accounting_db_pass"
  dbName: "accounting_db"
  sslmode: "disable"

  test:
    port: 5430
    user: "accounting_db"
    password: "test_accounting_db_pass"
    sslmode: "disable"
