version: '3.8'
services:
  accounting_service_db:
    image: postgres:latest
    container_name: accounting_service_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5430:5432'
    volumes:
      - ./accounting.sql:/docker-entrypoint-initdb.d/accounting.sql
  app:
    container_name: accounting-service
    build: .
    ports:
      - "8080:8080"
      - "140:140"
    restart: on-failure
    depends_on:
      - accounting_service_db
networks:
  default:
    external:
      name: delivery_app_net