server:
  address: ":8085"
  readTime: "5s"
  writeTime: "5s"
  idleTime: "5m"
  readerHeaderTime: "5s"

grpcServer:
  address: ":145"

services:
  # accounting: http://localhost:8080 # local run
  # restaurant: http://localhost:8086 # local run
  accounting: accounting-service:140 # docker run
  restaurant: restaurant-service:146 # docker run

database:
  # host: localhost # local run
  host: "host.docker.internal" # docker run
  port: 5435
  user: "order_db"
  password: "order_db_pass"
  dbName: "order_db"
  sslmode: "disable"

publisher:
  # url: amqp://guest:guest@localhost:5672 # local run
  url: amqp://guest:guest@host.docker.internal:5672 # docker run
