version: '3.8'
services:
  order_service_db:
    image: postgres:latest
    container_name: order_service_db
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5435:5432'
    volumes:
      - ./order.sql:/docker-entrypoint-initdb.d/order.sql
  app:
    container_name: order-service
    build: .
    ports:
      - "8085:8085"
      - "145:145"
    restart: on-failure
    depends_on:
      - order_service_db
networks:
  default:
    external:
      name: delivery_app_net
