version: '3.8'
services:
  app:
    container_name: kitchen-service
    build: .
    ports:
      - "8084:8084"
      - "144:144"
    restart: on-failure
networks:
  default:
    external:
      name: delivery_app_net
