// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: proto/delivery.proto

package delivery_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's data.
type EstimateDeliveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerID   int64 `protobuf:"varint,1,opt,name=ConsumerID,proto3" json:"ConsumerID,omitempty"`
	RestaurantID int64 `protobuf:"varint,2,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
}

func (x *EstimateDeliveryRequest) Reset() {
	*x = EstimateDeliveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_delivery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateDeliveryRequest) ProtoMessage() {}

func (x *EstimateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*EstimateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *EstimateDeliveryRequest) GetConsumerID() int64 {
	if x != nil {
		return x.ConsumerID
	}
	return 0
}

func (x *EstimateDeliveryRequest) GetRestaurantID() int64 {
	if x != nil {
		return x.RestaurantID
	}
	return 0
}

type EstimateDeliveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string  `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Cost float64 `protobuf:"fixed64,2,opt,name=Cost,proto3" json:"Cost,omitempty"`
}

func (x *EstimateDeliveryResponse) Reset() {
	*x = EstimateDeliveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_delivery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimateDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateDeliveryResponse) ProtoMessage() {}

func (x *EstimateDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateDeliveryResponse.ProtoReflect.Descriptor instead.
func (*EstimateDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateDeliveryResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *EstimateDeliveryResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type AssignOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID      int64 `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	FromUserID   int64 `protobuf:"varint,2,opt,name=FromUserID,proto3" json:"FromUserID,omitempty"`
	RestaurantID int64 `protobuf:"varint,3,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
}

func (x *AssignOrderRequest) Reset() {
	*x = AssignOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_delivery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignOrderRequest) ProtoMessage() {}

func (x *AssignOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignOrderRequest.ProtoReflect.Descriptor instead.
func (*AssignOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *AssignOrderRequest) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *AssignOrderRequest) GetFromUserID() int64 {
	if x != nil {
		return x.FromUserID
	}
	return 0
}

func (x *AssignOrderRequest) GetRestaurantID() int64 {
	if x != nil {
		return x.RestaurantID
	}
	return 0
}

type AssignOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID   int64 `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	CourierID int64 `protobuf:"varint,2,opt,name=CourierID,proto3" json:"CourierID,omitempty"`
}

func (x *AssignOrderResponse) Reset() {
	*x = AssignOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_delivery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignOrderResponse) ProtoMessage() {}

func (x *AssignOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignOrderResponse.ProtoReflect.Descriptor instead.
func (*AssignOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *AssignOrderResponse) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *AssignOrderResponse) GetCourierID() int64 {
	if x != nil {
		return x.CourierID
	}
	return 0
}

var File_proto_delivery_proto protoreflect.FileDescriptor

var file_proto_delivery_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x22,
	0x5d, 0x0a, 0x17, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x42,
	0x0a, 0x18, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x43, 0x6f,
	0x73, 0x74, 0x22, 0x72, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x4d, 0x0a, 0x13, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x49, 0x44, 0x32, 0xba, 0x01, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x12, 0x62, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x20, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_delivery_proto_rawDescOnce sync.Once
	file_proto_delivery_proto_rawDescData = file_proto_delivery_proto_rawDesc
)

func file_proto_delivery_proto_rawDescGZIP() []byte {
	file_proto_delivery_proto_rawDescOnce.Do(func() {
		file_proto_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_delivery_proto_rawDescData)
	})
	return file_proto_delivery_proto_rawDescData
}

var file_proto_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_delivery_proto_goTypes = []interface{}{
	(*EstimateDeliveryRequest)(nil),  // 0: courier.EstimateDeliveryRequest
	(*EstimateDeliveryResponse)(nil), // 1: courier.EstimateDeliveryResponse
	(*AssignOrderRequest)(nil),       // 2: courier.AssignOrderRequest
	(*AssignOrderResponse)(nil),      // 3: courier.AssignOrderResponse
}
var file_proto_delivery_proto_depIdxs = []int32{
	0, // 0: courier.Delivery.getEstimateDeliveryValues:input_type -> courier.EstimateDeliveryRequest
	2, // 1: courier.Delivery.assignOrder:input_type -> courier.AssignOrderRequest
	1, // 2: courier.Delivery.getEstimateDeliveryValues:output_type -> courier.EstimateDeliveryResponse
	3, // 3: courier.Delivery.assignOrder:output_type -> courier.AssignOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_delivery_proto_init() }
func file_proto_delivery_proto_init() {
	if File_proto_delivery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_delivery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateDeliveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_delivery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstimateDeliveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_delivery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_delivery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_delivery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_delivery_proto_goTypes,
		DependencyIndexes: file_proto_delivery_proto_depIdxs,
		MessageInfos:      file_proto_delivery_proto_msgTypes,
	}.Build()
	File_proto_delivery_proto = out.File
	file_proto_delivery_proto_rawDesc = nil
	file_proto_delivery_proto_goTypes = nil
	file_proto_delivery_proto_depIdxs = nil
}
