server:
  rest:
    address: ":8083"
    readTime: "5s"
    writeTime: "5s"
    idleTime: "5m"
    readerHeaderTime: "5s"
  grpc:
    address: ":143"

database:
  host: "host.docker.internal"
  port: 5433
  user: "delivery_db"
  password: "delivery_db_pass"
  dbName: "delivery_db"
  sslmode: "disable"

consumerServiceURl: host.docker.internal:141
courierServiceURl: host.docker.internal:142
restaurantServiceURl: host.docker.internal:146
googleApiKey: